# Generated by Django 3.0.6 on 2020-05-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('assistance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'assistance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_hour', models.TimeField(blank=True, null=True)),
                ('end_hour', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('inscription_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'inscription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('param_id', models.AutoField(primary_key=True, serialize=False)),
                ('param_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'param',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'role_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_app',
                'managed': False,
            },
        ),
    ]
